CREATE DATABASE [Amazon]

USE [Amazon]

CREATE TABLE [User](
[UserId] INT NOT NULL CONSTRAINT PK_User_UserId PRIMARY KEY IDENTITY(101,1),
[FirstName] NVARCHAR(100) NOT NULL,
[LastName] NVARCHAR(100) NOT NULL,
[Username] NVARCHAR(100) NOT NULL CONSTRAINT UQ_User_Username UNIQUE,
[Password] NVARCHAR(MAX) Not NULL,
[Email] NVARCHAR(100) NOT NULL CONSTRAINT UQ_User_Email UNIQUE,
[PhoneNo] NVARCHAR(10) CONSTRAINT UQ_User_PhoneNo UNIQUE,
[IsActive] BIT CONSTRAINT DF_User_IsActive DEFAULT 1,
[CreatedBy] INT NOT NULL CONSTRAINT DF_User_CreatedBy DEFAULT 1,
[CreatedOn] DATETIME NOT NULL CONSTRAINT DF_User_CreatedOn DEFAULT CURRENT_TIMESTAMP,
[UpdatedBy] INT,
[UpdatedOn] DATETIME
); 


CREATE TABLE [Product] (
[ProductId] INT NOT NULL CONSTRAINT PK_Product_ProductId PRIMARY KEY IDENTITY(101,1),
[Title] NVARCHAR(100) NOT NULL,
[Brand] NVARCHAR(100),
[Category] NVARCHAR(100) NOT NULL,
[Price] DECIMAL(12,2) NOT NULL,
[Rating] DECIMAL(3,1),
[IsActive] BIT CONSTRAINT DF_Product_IsActive DEFAULT 1,
[CreatedBy] INT NOT NULL CONSTRAINT DF_Product_CreatedBy DEFAULT 1,
[CreatedOn] DATETIME NOT NULL CONSTRAINT DF_Product_CreatedOn DEFAULT CURRENT_TIMESTAMP,
[UpdatedBy] INT,
[UpdatedOn] DATETIME
);

ALTER TABLE [Product]
ADD CONSTRAINT UQ_Product_Title_Category
UNIQUE (Title,Category)

CREATE TABLE [ProductDetail](
[ProductDetailId] INT NOT NULL CONSTRAINT PK_ProductDetail_ProductDetailId PRIMARY KEY IDENTITY(101,1),
[ProductId] INT NOT NULL
CONSTRAINT UQ_ProductDetail_ProductId UNIQUE
CONSTRAINT FK_ProductDetail_ProductId__Product_ProductId FOREIGN KEY(ProductId) REFERENCES [Product](ProductId) ON DELETE CASCADE,
[Description] NVARCHAR(MAX) NOT NULL,
[Stock] INT NOT NULL,
[sku] NVARCHAR(100) NOT NULL,
[Weight] DECIMAL(6,2) NOT NULL,
[Discount] INT,
[Warranty] NVARCHAR(100) NOT NULL,
[Shipping] NVARCHAR(100),
[ReturnPolicy] NVARCHAR(100) NOT NULL,
[IsActive] BIT CONSTRAINT DF_ProductDetail_IsActive DEFAULT 1,
[CreatedBy] INT NOT NULL CONSTRAINT DF_ProductDetail_CreatedBy DEFAULT 1,
[CreatedOn] DATETIME NOT NULL CONSTRAINT DF_ProductDetail_CreatedOn DEFAULT CURRENT_TIMESTAMP,
[UpdatedBy] INT,
[UpdatedOn] DATETIME
);

CREATE TABLE [Tags] (
[TagId] INT NOT NULL CONSTRAINT PK_Tags_TagId PRIMARY KEY IDENTITY(101,1),
[ProductId] INT NOT NULL
CONSTRAINT FK_Tags_ProductId__Product_ProductId FOREIGN KEY(ProductId) REFERENCES [Product](ProductId) ON DELETE CASCADE,
[Tag] NVARCHAR(MAX),
[IsActive] BIT CONSTRAINT DF_Tags_IsActive DEFAULT 1,
[CreatedBy] INT NOT NULL CONSTRAINT DF_Tags_CreatedBy DEFAULT 1,
[CreatedOn] DATETIME NOT NULL CONSTRAINT DF_Tags_CreatedOn DEFAULT CURRENT_TIMESTAMP,
[UpdatedBy] INT,
[UpdatedOn] DATETIME
);

CREATE TABLE [Images](
[ImageId] INT NOT NULL CONSTRAINT PK_Image_ImageId PRIMARY KEY IDENTITY(101,1),
[ProductId] INT NOT NULL
CONSTRAINT FK_Images_ProductId__Product_ProductId FOREIGN KEY(ProductId) REFERENCES [Product](ProductId) ON DELETE CASCADE,
[ImageTypeId] INT NOT NULL CONSTRAINT DF_Image_ImageTypeId DEFAULT 101
CONSTRAINT FK_Image_ImageTypeId__ImageType_ImageTypeId FOREIGN KEY (ImageTypeId) REFERENCES [ImageType](ImageTypeId) ON DELETE CASCADE,
[Image] VARBINARY(MAX),
[ImageName] NVARCHAR(100),
[ImageType] NVARCHAR(100),
[IsActive] BIT CONSTRAINT DF_Images_IsActive DEFAULT 1,
[CreatedBy] INT NOT NULL CONSTRAINT DF_Images_CreatedBy DEFAULT 1,
[CreatedOn] DATETIME NOT NULL CONSTRAINT DF_Images_CreatedOn DEFAULT CURRENT_TIMESTAMP,
[UpdatedBy] INT,
[UpdatedOn] DATETIME
);

CREATE TABLE [Reviews] (
[ReviewId] INT NOT NULL CONSTRAINT PK_Review_ReviewId PRIMARY KEY IDENTITY(101,1),
[ProductId] INT NOT NULL
CONSTRAINT FK_Reviews_ProductId__Product_ProductId FOREIGN KEY(ProductId) REFERENCES [Product](ProductId) ON DELETE CASCADE,
[ReviewrName] NVARCHAR(100) NOT NULL,
[ReviewerEmail] NVARCHAR(100) NOT NULL CONSTRAINT UQ_Reviews_ReviewerEmail UNIQUE,
[Comment] NVARCHAR(MAX),
[Rating] DECIMAL(3,1),
[IsActive] BIT CONSTRAINT DF_Reviews_IsActive DEFAULT 1,
[CreatedBy] INT NOT NULL CONSTRAINT DF_Reviews_CreatedBy DEFAULT 1,
[CreatedOn] DATETIME NOT NULL CONSTRAINT DF_Reviews_CreatedOn DEFAULT CURRENT_TIMESTAMP,
[UpdatedBy] INT,
[UpdatedOn] DATETIME
);

CREATE TABLE [Order](
[OrderId] INT NOT NULL CONSTRAINT PK_Order_OrderId PRIMARY KEY IDENTITY(101,1),
[UserId] INT NOT NULL CONSTRAINT FK_Order_UserId__User_UserId FOREIGN KEY(UserId) REFERENCES [User](UserId) ON DELETE CASCADE,
[ProductId] INT NOT NULL CONSTRAINT FK_Order_ProductId__Product_ProductId FOREIGN KEY(ProductId) REFERENCES [Product](ProductId) ON DELETE CASCADE,
[IsActive] BIT CONSTRAINT DF_Order_IsActive DEFAULT 1,
[CreatedBy] INT NOT NULL CONSTRAINT DF_Order_CreatedBy DEFAULT 1,
[CreatedOn] DATETIME NOT NULL CONSTRAINT DF_Order_CreatedOn DEFAULT CURRENT_TIMESTAMP,
[UpdatedBy] INT,
[UpdatedOn] DATETIME
);

CREATE TABLE [Cart](
[CartId] INT NOT NULL CONSTRAINT PK_Cart_CartId PRIMARY KEY IDENTITY(101,1),
[UserId] INT NOT NULL
CONSTRAINT UQ_Cart_UserId UNIQUE 
CONSTRAINT FK_Cart_UserId__User_UserId FOREIGN KEY(UserId) REFERENCES [User](UserId) ON DELETE CASCADE,
[IsActive] BIT CONSTRAINT DF_Cart_IsActive DEFAULT 1,
[CreatedBy] INT NOT NULL CONSTRAINT DF_Cart_CreatedBy DEFAULT 1,
[CreatedOn] DATETIME NOT NULL CONSTRAINT DF_Cart_CreatedOn DEFAULT CURRENT_TIMESTAMP,
[UpdatedBy] INT,
[UpdatedOn] DATETIME
);

CREATE TABLE [UserCart](
[UserCartId] INT NOT NULL CONSTRAINT PK_UserCart_UserCartId PRIMARY KEY IDENTITY(101,1),
[CartId] INT NOT NULL CONSTRAINT FK_UserCart_CartId_Cart_CartId FOREIGN KEY(CartId) REFERENCES [Cart](CartId) ON DELETE CASCADE,
[ProductId] INT NOT NULL CONSTRAINT FK_UserCart_ProductId__Product_ProdcutId FOREIGN KEY (ProductId) REFERENCES [Product](ProductId) ON DELETE CASCADE,
[IsActive] BIT CONSTRAINT DF_UserCart_IsActive DEFAULT 1,
[CreatedBy] INT NOT NULL CONSTRAINT DF_UserCart_CreatedBy DEFAULT 1,
[CreatedOn] DATETIME NOT NULL CONSTRAINT DF_UserCart_CreatedOn DEFAULT CURRENT_TIMESTAMP,
[UpdatedBy] INT,
[UpdatedOn] DATETIME
);

CREATE TABLE [ImageType](
[ImageTypeId] INT NOT NULL CONSTRAINT PK_ImageType_ImageTypeId PRIMARY KEY IDENTITY(101,1),
[Name] NVARCHAR(50) NOT NULL,
[Description] NVARCHAR(150),
[IsActive] BIT CONSTRAINT DF_ImageType_IsActive DEFAULT 1,
[CreatedBy] INT NOT NULL CONSTRAINT DF_ImageType_CreatedBy DEFAULT 1,
[CreatedOn] DATETIME NOT NULL CONSTRAINT DF_ImageType_CreatedOn DEFAULT CURRENT_TIMESTAMP,
[UpdatedBy] INT,
[UpdatedOn] DATETIME
);

